name: Build and Release
on:
  push:
    branches:
      - feat/vercel_deployment_script
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build React app
        run: pnpm run build:widget && pnpm run build:app

      - name: Archive build
        run: tar -czf dist.tar.gz app/dist widget/dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist.tar.gz
